resources:
- name: repo
  type: git
  source:
    uri: https://github.com/instana/go-sensor.git
    branch: main

jobs:
- name: run-tests-job
  plan:
  - get: repo
    trigger: true

  - task: run-tests-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
          tag: latest
      inputs:
      - name: repo
      run:
        path: sh
        args:
        - -cx
        - |
          cd repo
          make test

